import plantCellRender from '../assets/cell-plant-render.png'

export const CELL_TYPES = [
  { id: 'plant', name: 'Porsche 911 Turbo S', type: 'German Sports Car', accent: '#82b366' },
  { id: 'white-blood', name: 'Mercedes-AMG G63', type: 'Luxury SUV', accent: '#7e6edb' },
  { id: 'neuron', name: 'Toyota GR Supra', type: 'Japanese Sports Car', accent: '#8b5cf6' },
  { id: 'epithelial', name: 'Ford F-150 Raptor', type: 'Performance Pickup', accent: '#e07a7a' },
  { id: 'bacteria', name: 'Tesla Model S Plaid', type: 'Electric Performance Sedan', accent: '#5fbf9f' },
  { id: 'animal', name: 'BMW i8 Roadster', type: 'Hybrid Sports Car', accent: '#459ccf' },
  { id: 'muscle', name: 'Dodge Challenger Hellcat', type: 'American Muscle Car', accent: '#d25762' },
]

export const SEEDED_GENERATED_CELLS = [
  {
    id: 'tripo-porsche-911',
    name: 'Porsche 911 Turbo S',
    type: 'AI Generated Model',
    accent: '#82b366',
    custom: true,
    template: 'plant',
    imageUrl: '/generated-models/car-reference-images/porsche-911-turbo-s.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'porsche-911-turbo-s',
      modelUrl: '/generated-models/porsche-911-turbo-s.glb',
      rawModelUrl: '',
      message: 'AI-generated Porsche 911 Turbo S via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-mercedes-g63',
    name: 'Mercedes-AMG G63',
    type: 'AI Generated Model',
    accent: '#7e6edb',
    custom: true,
    template: 'white-blood',
    imageUrl: '/generated-models/car-reference-images/mercedes-amg-g63.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'mercedes-amg-g63',
      modelUrl: '/generated-models/mercedes-amg-g63.glb',
      rawModelUrl: '',
      message: 'AI-generated Mercedes-AMG G63 via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-toyota-supra',
    name: 'Toyota GR Supra',
    type: 'AI Generated Model',
    accent: '#8b5cf6',
    custom: true,
    template: 'neuron',
    imageUrl: '/generated-models/car-reference-images/toyota-gr-supra.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'toyota-gr-supra',
      modelUrl: '/generated-models/toyota-gr-supra.glb',
      rawModelUrl: '',
      message: 'AI-generated Toyota GR Supra via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-ford-raptor',
    name: 'Ford F-150 Raptor',
    type: 'AI Generated Model',
    accent: '#e07a7a',
    custom: true,
    template: 'epithelial',
    imageUrl: '/generated-models/car-reference-images/ford-f150-raptor.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'ford-f150-raptor',
      modelUrl: '/generated-models/ford-f150-raptor.glb',
      rawModelUrl: '',
      message: 'AI-generated Ford F-150 Raptor via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-tesla-plaid',
    name: 'Tesla Model S Plaid',
    type: 'AI Generated Model',
    accent: '#5fbf9f',
    custom: true,
    template: 'bacteria',
    imageUrl: '/generated-models/car-reference-images/tesla-model-s-plaid.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'tesla-model-s-plaid',
      modelUrl: '/generated-models/tesla-model-s-plaid.glb',
      rawModelUrl: '',
      message: 'AI-generated Tesla Model S Plaid via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-bmw-i8',
    name: 'BMW i8 Roadster',
    type: 'AI Generated Model',
    accent: '#459ccf',
    custom: true,
    template: 'animal',
    imageUrl: '/generated-models/car-reference-images/bmw-i8-roadster.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'bmw-i8-roadster',
      modelUrl: '/generated-models/bmw-i8-roadster.glb',
      rawModelUrl: '',
      message: 'AI-generated BMW i8 Roadster via Tripo image-to-3D.',
    },
  },
  {
    id: 'tripo-dodge-hellcat',
    name: 'Dodge Challenger Hellcat',
    type: 'AI Generated Model',
    accent: '#d25762',
    custom: true,
    template: 'muscle',
    imageUrl: '/generated-models/car-reference-images/dodge-challenger-hellcat.png',
    generation: {
      provider: 'tripo',
      status: 'success',
      taskId: 'dodge-challenger-hellcat',
      modelUrl: '/generated-models/dodge-challenger-hellcat.glb',
      rawModelUrl: '',
      message: 'AI-generated Dodge Challenger Hellcat via Tripo image-to-3D.',
    },
  },
]

export const KHRONOS_REFERENCE_CELLS = [
  {
    id: 'khronos-transmission-test',
    name: '玻璃材质测试',
    type: 'Khronos 材质参考',
    accent: '#72a4bf',
    custom: true,
    reference: true,
    template: 'animal',
    imageUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/TransmissionTest/screenshot/screenshot_large.png',
    referenceSummary: 'Khronos glTF sample for transparent materials. Useful for tuning glass bodies, headlight lenses, and window transparency.',
    referenceLicense: 'CC0, Adobe via Khronos glTF Sample Models',
    referenceSource: 'https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TransmissionTest',
    generation: {
      provider: 'reference',
      requestedProvider: 'reference',
      status: 'success',
      taskId: 'khronos-transmission-test',
      modelUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/TransmissionTest/glTF-Binary/TransmissionTest.glb',
      rawModelUrl: '',
      message: 'Remote Khronos GLB reference for transparent material behavior.',
    },
  },
  {
    id: 'khronos-transmission-roughness',
    name: '磨砂玻璃测试',
    type: 'Khronos 材质参考',
    accent: '#8eb4cf',
    custom: true,
    reference: true,
    template: 'animal',
    imageUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/TransmissionRoughnessTest/screenshot/screenshot-large.png',
    referenceSummary: 'Khronos glTF sample for transmission, IOR, and roughness. Useful for frosted windows, light diffusers, and soft translucent panels.',
    referenceLicense: 'CC-BY 4.0, Ed Mackey / Analytical Graphics via Khronos glTF Sample Models',
    referenceSource: 'https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TransmissionRoughnessTest',
    generation: {
      provider: 'reference',
      requestedProvider: 'reference',
      status: 'success',
      taskId: 'khronos-transmission-roughness',
      modelUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/TransmissionRoughnessTest/glTF-Binary/TransmissionRoughnessTest.glb',
      rawModelUrl: '',
      message: 'Remote Khronos GLB reference for IOR and translucent roughness.',
    },
  },
  {
    id: 'khronos-mosquito-amber',
    name: '琥珀标本模型',
    type: 'Khronos 参考模型',
    accent: '#d18a42',
    custom: true,
    reference: true,
    template: 'bacteria',
    imageUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/MosquitoInAmber/screenshot/screenshot.jpg',
    referenceSummary: 'Biological specimen in transparent amber. Useful for organic detail plus translucent material presentation.',
    referenceLicense: 'CC-BY 4.0, Loic Norgeot / Geoffrey Marchal / Sketchfab via Khronos glTF Sample Models',
    referenceSource: 'https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/MosquitoInAmber',
    generation: {
      provider: 'reference',
      requestedProvider: 'reference',
      status: 'success',
      taskId: 'khronos-mosquito-amber',
      modelUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/main/2.0/MosquitoInAmber/glTF-Binary/MosquitoInAmber.glb',
      rawModelUrl: '',
      message: 'Remote Khronos GLB reference. This model is larger and may take longer to load.',
    },
  },
]

export const ORGANELLES = {
  nucleus: {
    label: 'Powertrain',
    title: 'Powertrain',
    subtitle: 'Engine and drivetrain core',
    size: 'Central mechanical assembly',
    location: 'Front or mid-mounted',
    visible: 'Visible in inspection mode',
    note: 'The powertrain is the heart of the vehicle. It defines performance character, sound, and driving dynamics.',
    accent: '#7b4bb4',
  },
  lysosome: {
    label: 'Wheels & Brakes',
    title: 'Wheels & Brakes',
    subtitle: 'Rolling stock and braking system',
    size: 'Four corner assemblies',
    location: 'At each corner of the chassis',
    visible: 'Always visible externally',
    note: 'Wheels and brakes define the car\'s stance and stopping power. Alloy designs are a key visual differentiator.',
    accent: '#8d58b8',
  },
  mitochondria: {
    label: 'Exhaust System',
    title: 'Exhaust System',
    subtitle: 'Exhaust routing and tips',
    size: 'Medium assembly along underside',
    location: 'Underbody to rear',
    visible: 'Visible at rear and underside',
    note: 'The exhaust system contributes to the car\'s acoustic signature and rear visual design through tip placement.',
    accent: '#df7046',
  },
  membrane: {
    label: 'Body Shell',
    title: 'Body Shell',
    subtitle: 'Exterior panels and silhouette',
    size: 'Full vehicle envelope',
    location: 'Entire exterior surface',
    visible: 'Always visible',
    note: 'The body shell defines the car\'s character lines, proportions, and aerodynamic profile. It\'s the primary visual identity.',
    accent: '#7aa4bf',
  },
  granules: {
    label: 'Interior & Trim',
    title: 'Interior & Trim',
    subtitle: 'Cabin, dashboard, and detail trim',
    size: 'Cabin volume and accent pieces',
    location: 'Inside the cabin and exterior trim',
    visible: 'Visible through windows and open views',
    note: 'Interior quality and trim details distinguish premium vehicles. Materials, stitching, and layout define the cabin experience.',
    accent: '#5b82c4',
  },
}

export const ORGANELLE_ORDER = ['nucleus', 'lysosome', 'mitochondria', 'membrane', 'granules']

export const MICROSCOPE_IMAGES = [
  { label: '工作室预览', tone: 'light', note: '适合截图的干净展示视角。' },
  { label: '材质通道', tone: 'purple', note: '材质和颜色分离预览。' },
  { label: '深度预览', tone: 'mono', note: '形状和立体感预览。' },
]

export const WORKSPACE_PANELS = {
  Gallery: '保存的渲染角度、缩略图和导出的展示截图。',
  Library: '展厅车型、生成资产、本地导入和参考 GLB 文件。',
  Notebooks: '与当前车型和检查部件关联的笔记。',
  Logs: '诊断信息、API 请求日志和生成问题排查。',
  Settings: '查看器质量、服务商默认值、截图尺寸和导出偏好。',
  Compare: '并排模型对比：形状、材质和生成质量。',
  Profile: '当前工作区：3D 汽车展厅。',
}

export const CELL_PROFILES = {
  plant: {
    summary: 'Iconic German sports car with rear-engine layout, twin-turbo flat-six producing 640 hp, and legendary 911 silhouette. The Turbo S represents the pinnacle of the 911 lineup.',
    occurs: 'High-performance sports cars, track-capable grand tourers, and automotive icons.',
    comparison: 'Rear-engine layout and flat-six heritage distinguish it from front-engine sports cars; more refined than raw supercars.',
    compareTarget: 'neuron',
    organelles: ['membrane', 'nucleus', 'mitochondria', 'granules'],
  },
  'white-blood': {
    summary: 'Legendary luxury SUV with boxy design, handcrafted AMG twin-turbo V8 producing 577 hp, and unmatched off-road capability. The G-Wagon combines military heritage with modern luxury.',
    occurs: 'Luxury SUVs, off-road capable vehicles, and status symbols.',
    comparison: 'Boxy military-inspired design and three locking differentials set it apart from crossovers; more capable off-road than any luxury SUV.',
    compareTarget: 'epithelial',
    organelles: ['lysosome', 'nucleus', 'mitochondria', 'membrane', 'granules'],
  },
  neuron: {
    summary: 'Modern Japanese sports car co-developed with BMW, featuring turbocharged inline-6 producing 382 hp, long hood, and aggressive aerodynamics. Revives the legendary Supra nameplate.',
    occurs: 'Sports cars, tuner favorites, and modern performance coupes.',
    comparison: 'Inline-6 turbo and rear-wheel drive layout echo classic sports car formula; more accessible than supercars, sharper than grand tourers.',
    compareTarget: 'muscle',
    organelles: ['membrane', 'nucleus', 'mitochondria', 'granules'],
  },
  epithelial: {
    summary: 'High-performance off-road pickup with twin-turbo V6 producing 450 hp, FOX Racing shocks, and Baja-inspired design. The Raptor dominates desert racing and extreme terrain.',
    occurs: 'Performance trucks, off-road vehicles, and desert racing machines.',
    comparison: 'Long-travel suspension and desert-racing DNA separate it from work trucks; more capable off-road than luxury SUVs.',
    compareTarget: 'white-blood',
    organelles: ['membrane', 'nucleus', 'mitochondria', 'granules'],
  },
  bacteria: {
    summary: 'Revolutionary electric performance sedan with tri-motor all-wheel drive producing 1,020 hp, 0-60 mph in 1.99 seconds, and over 400 miles of range. Redefines electric performance.',
    occurs: 'Electric vehicles, performance sedans, and technology showcases.',
    comparison: 'Instant torque and silent acceleration distinguish it from combustion sports cars; faster than most supercars in a straight line.',
    compareTarget: 'plant',
    organelles: ['membrane', 'nucleus', 'granules'],
  },
  animal: {
    summary: 'Futuristic hybrid sports car with plug-in powertrain producing 369 hp, iconic butterfly doors, and aerospace-inspired design. The i8 showcases BMW\'s vision of sustainable performance.',
    occurs: 'Hybrid sports cars, design showcases, and eco-performance vehicles.',
    comparison: 'Hybrid powertrain and futuristic styling set it apart from traditional sports cars; more efficient than pure combustion, more dramatic than conventional hybrids.',
    compareTarget: 'neuron',
    organelles: ['membrane', 'nucleus', 'mitochondria', 'granules'],
  },
  muscle: {
    summary: 'American muscle icon with supercharged 6.2L HEMI V8 producing 717+ hp, aggressive retro styling, and tire-shredding performance. The Hellcat embodies raw, unfiltered power.',
    occurs: 'American muscle cars, drag racing machines, and performance legends.',
    comparison: 'Supercharged V8 roar and straight-line brutality distinguish it from refined sports cars; more aggressive and louder than European performance coupes.',
    compareTarget: 'neuron',
    organelles: ['membrane', 'nucleus', 'mitochondria', 'granules'],
  },
}

export const DEFAULT_ORGANELLE_BY_CELL = {
  plant: 'membrane',
  'white-blood': 'lysosome',
  neuron: 'nucleus',
  epithelial: 'membrane',
  bacteria: 'granules',
  animal: 'nucleus',
  muscle: 'mitochondria',
}

export const CELL_DETAIL_OVERRIDES = {
  plant: {
    nucleus: {
      subtitle: 'Twin-turbo flat-six engine',
      size: '3.8L displacement, 640 hp',
      location: 'Rear-mounted, longitudinal',
      visible: 'Yes',
      note: 'The legendary flat-six sits behind the rear axle, delivering instant throttle response and that unmistakable Porsche howl. Twin turbos provide massive torque across the rev range.',
      funFact: 'The 911 Turbo S can accelerate from 0-60 mph in just 2.6 seconds.',
    },
    membrane: {
      title: 'Body Panels',
      subtitle: 'Aluminum and composite exterior',
      size: 'Full sports car envelope',
      location: 'Entire exterior surface',
      visible: 'Yes',
      note: 'The iconic 911 silhouette features wide rear fenders, active aerodynamics, and a sloping roofline that has evolved over 60 years while remaining instantly recognizable.',
      funFact: 'The 911 design has remained remarkably consistent since 1963, making it one of the most recognizable sports cars ever.',
    },
    mitochondria: {
      note: 'The sport exhaust system features active valves that open under acceleration, unleashing the full flat-six symphony while remaining civilized in comfort mode.',
      funFact: 'Porsche offers a sport exhaust option that adds even more volume and character to the flat-six sound.',
    },
    granules: {
      title: 'Cabin & Dashboard',
      subtitle: 'Driver-focused cockpit',
      note: 'The interior blends classic 911 design cues with modern technology, featuring a central tachometer, sport seats, and premium materials throughout.',
      funFact: 'The 911 maintains its iconic five-gauge instrument cluster design, with the tachometer always in the center.',
    },
  },
  'white-blood': {
    lysosome: {
      note: 'The G-Wagon rides on massive wheels with three locking differentials, providing unmatched traction on any terrain from desert sand to mountain trails.',
      funFact: 'The G-Class can ford water up to 27.5 inches deep and climb 45-degree slopes.',
    },
    nucleus: {
      note: 'The handcrafted AMG 4.0L twin-turbo V8 produces 577 hp and 627 lb-ft of torque, delivering effortless acceleration despite the G-Wagon\'s substantial weight.',
      funFact: 'Each AMG engine is hand-built by a single technician and bears their signature on the engine cover.',
    },
    membrane: {
      title: 'Boxy Body Shell',
      subtitle: 'Military-heritage design',
      note: 'The G-Wagon\'s iconic boxy shape has remained largely unchanged since 1979, combining military ruggedness with modern luxury and LED lighting.',
      funFact: 'The G-Class was originally developed as a military vehicle in the 1970s.',
    },
  },
  neuron: {
    membrane: {
      title: 'Aero Body & Spoiler',
      subtitle: 'Wind-tunnel-tuned panels',
      location: 'Full exterior with active aero',
      note: 'The GR Supra features aggressive aerodynamics with a double-bubble roof, functional vents, and an active rear spoiler that deploys at speed for maximum downforce.',
      funFact: 'The Supra\'s design was refined in the same wind tunnel used for NASCAR and Formula 1 development.',
    },
    nucleus: {
      subtitle: 'Turbocharged inline-6 engine',
      size: '3.0L displacement, 382 hp',
      location: 'Front-mounted, longitudinal',
      note: 'The BMW-sourced B58 inline-6 turbo delivers smooth power delivery with massive tuning potential, making it a favorite among enthusiasts.',
      funFact: 'The Supra\'s engine can be tuned to over 600 hp with simple modifications.',
    },
  },
  epithelial: {
    membrane: {
      title: 'Truck Bed & Cab',
      subtitle: 'Baja-inspired exterior',
      location: 'Crew cab and reinforced bed',
      note: 'The Raptor features flared fenders, FORD block lettering in the grille, and aggressive styling inspired by desert racing. The bed includes integrated tie-downs and LED lighting.',
      funFact: 'The Raptor is named after the velociraptor dinosaur, emphasizing its predatory performance.',
    },
    nucleus: {
      subtitle: 'Twin-turbo V6 engine',
      size: '3.5L EcoBoost, 450 hp',
      location: 'Front-mounted, transverse',
      note: 'The high-output EcoBoost V6 delivers massive torque for desert running and towing, paired with a 10-speed automatic transmission.',
      funFact: 'The Raptor\'s engine produces 510 lb-ft of torque, more than many V8 trucks.',
    },
  },
  bacteria: {
    granules: {
      title: 'Minimalist Cabin',
      subtitle: 'Tech-forward interior',
      size: 'Spacious five-seat layout',
      location: 'Inside the aerodynamic body',
      note: 'The Model S Plaid features a yoke steering wheel, 17-inch central touchscreen, and premium materials. The minimalist design emphasizes the massive screen and open space.',
      funFact: 'The Model S Plaid can play AAA video games on its center screen with console-level graphics.',
    },
    nucleus: {
      subtitle: 'Tri-motor electric powertrain',
      size: '1,020 hp combined output',
      location: 'Front and rear motors',
      note: 'Three electric motors (one front, two rear) deliver instant torque to all four wheels, enabling the fastest production sedan acceleration in the world.',
      funFact: 'The Model S Plaid can reach 200 mph and complete a quarter-mile in under 9 seconds.',
    },
  },
  animal: {
    nucleus: {
      note: 'The i8\'s plug-in hybrid system combines a turbocharged 1.5L three-cylinder with an electric motor, producing 369 hp total while achieving impressive fuel economy.',
      funFact: 'The i8 can drive up to 18 miles on electric power alone.',
    },
    membrane: {
      title: 'Futuristic Body Shell',
      subtitle: 'Aerospace-inspired design',
      note: 'The i8 features dramatic butterfly doors, flowing lines, and a carbon fiber passenger cell. The design language previews BMW\'s electric future.',
      funFact: 'The i8\'s body uses carbon fiber reinforced plastic (CFRP) to keep weight down despite the hybrid powertrain.',
    },
  },
  muscle: {
    mitochondria: {
      note: 'A free-flowing dual exhaust system with massive tips produces the signature supercharged V8 roar that defines the Hellcat experience. The sound is unmistakable and intoxicating.',
      funFact: 'The Hellcat\'s exhaust note is so loud it can trigger car alarms in parking lots.',
    },
    nucleus: {
      subtitle: 'Supercharged HEMI V8',
      size: '6.2L displacement, 717+ hp',
      location: 'Front-mounted, longitudinal',
      note: 'The supercharged HEMI V8 is a modern interpretation of classic American muscle, with a 2.7L supercharger force-feeding massive amounts of air for tire-shredding power.',
      funFact: 'The Hellcat Redeye variant produces 797 hp, making it one of the most powerful production cars ever.',
    },
  },
}

export const CELL_BODY = {
  plant: { color: '#c8d8e8', scale: [1.38, 1.04, 0.76], kind: 'box' },
  'white-blood': { color: '#8b9dc3', scale: [1.34, 1.18, 0.92], kind: 'sphere' },
  neuron: { color: '#d42626', scale: [0.78, 0.68, 0.58], kind: 'sphere' },
  epithelial: { color: '#7a8b6e', scale: [1.22, 0.92, 0.52], kind: 'box' },
  bacteria: { color: '#f0c75e', scale: [0.9, 1, 0.56], kind: 'capsule' },
  animal: { color: '#2c2c2c', scale: [1.18, 1.08, 0.9], kind: 'sphere' },
  muscle: { color: '#e04040', scale: [0.82, 1.1, 0.48], kind: 'capsule' },
}
